{% set name = "jh2" %}
{% set version = "5.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jh2-{{ version }}.tar.gz
  sha256: ad91f57c3485d87a8edee558dafab0f08c716857d748731c0998dcefe9d3fd5f

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
  run:
    - python

test:
  imports:
    - jh2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jawah/h2
  summary: HTTP/2 State-Machine based protocol implementation
  license: MIT
  license_file:
    - LICENSE
    - tests/http2-frame-test-case/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - rxm7706
